# Introduction to PyTorch

This notebook was adapted from [Stanford's CS224N Pytorch](https://github.com/SunnyHaze/Stanford-CS224N-NLP/blob/main/CS224N%20PyTorch%20Tutorial.ipynb) Tutorial by Dilara Soylu as well as the official [PyTorch 60 Minute Blitz Tutorial](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) demo for PyTorch.

We will have a basic introduction to `PyTorch` and Tensors and how to use them to create, train and evaluate Neural Networks. In the end, we will build, train, and evaluate our first classifier by classifying two moons!

## Introduction
[PyTorch](https://pytorch.org/) is a machine learning framework that is used in both academia and industry for various applications. PyTorch started of as a more flexible alternative to [TensorFlow](https://www.tensorflow.org/), which is another popular machine learning framework. At the time of its release, `PyTorch` appealed to the users due to its user friendly nature: as opposed to defining static graphs before performing an operation as in `TensorFlow`, `PyTorch` allowed users to define their operations as they go, which is also the approached integrated by `TensorFlow` in its following releases. Although `TensorFlow` is more widely preferred in the industry, `PyTorch` is often times the preferred machine learning framework for researchers.

Now that we have learned enough about the background of `PyTorch`, let's start by importing it into our notebook.

In [8]:
import torch
import torch.nn as nn # contains functionality for building neural networks
import numpy as np

Like in the last notebook, we can use `__version__` to check the `PyTorch` version that Colab is running on.

In [9]:
torch.__version__

'2.6.0+cu124'

PyTorch is open source and the documentation can he accessed [here](https://pytorch.org/docs/stable/index.html). With it imported, we can get started!

## Tensors

Tensors are the most basic building blocks in `PyTorch`. Tensors are similar to matrices, but the have extra properties and they can represent higher dimensions. For example, an square RGB image with 256 pixels in both sides can be represented by a 3x256x256 tensor, where the first 3 dimensions represent the color channels RGB. In `PyTorch`, we often use tensors to encode the inputs and outputs of a neural network model, as well as the model's parameters, to a numeric format which can be understood by the architecture. Tensors can run on GPU's to accelerate e.g. network training.

### Tensor Initialization

There are several ways to instantiate tensors:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.

In [20]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [21]:
print(type(x_data)) # prints the type of the data structure, i.e. tensor
print(x_data.dtype) # print type of elements in the tensor

<class 'torch.Tensor'>
torch.int64


We can also speficy the data type (`dtype`) directly:

In [23]:
# We are using the dtype to create a float tensor
x_float = torch.tensor(data, dtype=torch.float)
x_float.dtype

torch.float32

**From a Python List**

We can initalize a tensor from a Python list, which could include sublists. The dimensions and the data types will be automatically inferred by PyTorch when we use torch.tensor().

In [14]:
# Initialize a tensor from a Python List
data = [
        [0, 1],
        [2, 3],
        [4, 5]
       ]
x_python = torch.tensor(data)

# Print the tensor
x_python

tensor([[0, 1],
        [2, 3],
        [4, 5]])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa).

In [12]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.

In [13]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2647, 0.2573],
        [0.7728, 0.3872]]) 



**With random or constant values:**

Similar to what we have seen with NumPy, we can pre-fill tensors with static values like 1, or random numbers, just such that we have the shape as a placeholder. For this, we define `shape` as a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.

In [28]:
shape = (2, 3,) # 2x3x1 = 2x3 tensor
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

# to read the dimensions of a tensor, use shape or size()
print(zeros_tensor.shape)
print(zeros_tensor.size())

Random Tensor: 
 tensor([[0.4318, 0.0143, 0.3679],
        [0.8153, 0.1362, 0.0358]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.Size([2, 3])


### Tensor Attributes

Tensors have several attributes which are important to know and adjust to your needs. Some of these properties are the aforementioned `shape`, `dtype` and the `device` they are stored on. The device could for instance be a CPU or a GPU. During training of neural networks, we might want to push our tensors onto the GPU device for accelerated training. Let's look at these tensor attributes below: